# This gets included at the beginning of the Planck's Makefile.
# Alternatively, you can run make from the keymap directory
# and the main Makefile will be included after.

TAP_DANCE_ENABLE = yes

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
